### ISSUE TITLE
Maven takes too long to download

### ISSUE THREAD

**Issue by Drawethree** [CodeMC/WorldGuardWrapper#10]
Issue is selfexplaining, it takes too long to download when building.

**Comment by sgdc3** [comment]
This is so strange, can you show me your pom?

**Comment by Drawethree** [comment]
Sure. Here  https://hastebin.com/eveyamavaz.xml

pi 26. 4. 2019 o 13:28 Gabriele C. <notifications@github.com> napísal(a):

**Comment by sgdc3** [comment]
can you please post the maven log?
