### ISSUE TITLE
1.16 WorldGuardWrapper 

### ISSUE THREAD

**Issue by iSkyify** [CodeMC/WorldGuardWrapper#40]
Hey, can you please update this to support the latest 1.16 WG build on https://builds.enginehub.org/job/worldguard ?

**Comment by stijnb1234** [comment]
Should be implemented in #34

**Comment by iSkyify** [comment]
Can the author merge that pull request?  #34

**Comment by sgdc3** [comment]
@iSkyify WGW should already support 1.16 builds, as the WG api didn't change
